# Generated by Django 2.1.7 on 2019-09-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boards', '0003_auto_20190828_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='lists_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='list',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
